---
title: "Further data science training resources"
output:
  html_document:
    toc: yes
    toc_float: true
    toc_depth: 5
date: "24/10/2022"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Training for beginners  

If you are completely new to coding, you can get an overview of different coding languages through the Government Analysis Function [here](https://analysisfunction.civilservice.gov.uk/training/awareness-of-new-coding-tools/).  

If you have not coded before, there are lots of resources you can use to get you started. We recommend you take a look at [courses from the Government Analysis Function](https://analysisfunction.civilservice.gov.uk/training-courses/?keyword=&training_category=&type=online&participation=&provider=&training_location=&submit=Go). These courses are open to analysts and scientists working in government. 

## R and RStudio training 

There is a whole host of introductory courses for R and RStudio including:  

* [Introduction to R course](https://analysisfunction.civilservice.gov.uk/training/introduction-to-r/)  
    + For this course you need to be able to access R and RStudio, and some packages installed, and upload some data  
    + This is described in [Getting started with RStudio in CDAP](https://defra-data-science-centre-of-excellence.github.io/CDAP_training/RStudio_in_CDAP/getting_started/), so have a look at this together with the precourse information  
    + Do not install packages as described in the precourse information but follow the CDAP-specific instructions  
    + Upload the data as described in the CDAP specific information  
* [Data visualisation in R and Python](https://analysisfunction.civilservice.gov.uk/training/data-visualisation-in-r-and-python/)  
* [Data linkage in R](https://analysisfunction.civilservice.gov.uk/training/data-linkage-in-r/)  
* [R control flow loops and functions](https://analysisfunction.civilservice.gov.uk/training/r-control-flow-loops-and-functions/)  
* [Data linkage in R](https://analysisfunction.civilservice.gov.uk/training/introduction-to-sparklyr/)  


## Python training

Just like for R, the Government Analysis Function offer lots of courses in Python:  

* [Introduction to Python](https://analysisfunction.civilservice.gov.uk/training/introduction-to-python/)  
    + Perform basic coding  
    + Import & export data  
    + Manipulate basic Data  
    + Perform a linear regression  
    + Basic visualisation  

* [Editing & imputation in Python](https://analysisfunction.civilservice.gov.uk/training/editing-and-imputation-in-python/)  
    + Identifying missing values, visualising the missing value & finding duplicates in data.  
    + Auto editing where you can apply restrictions, check which restrictions have been violated and correct them.  
    + Impute missing values using model-based methods such as mean, meadian, ratio & regression imputation.  
    + Impute missing values using donor-based imputations such as: random hot-deck, sequential hot-deck, hierarchical hot-deck & K-nearest neighbours imputation.  

* [Python control flow loops & functions](https://analysisfunction.civilservice.gov.uk/training/python-control-flow-loops-and-functions/)  
    + Use For & While loops  
    + Use If, Elif & Else Control Flow  
    + Write your own basic functions  
    + Awareness of how functions can be applied to DataFrames  
    
## SQL Training  
The Government Analysis Function offers just the one course for SQL:  

* [Foundations of SQL](https://analysisfunction.civilservice.gov.uk/training/foundations-of-sql/). This course will give you experience using the SQL methods of database querying, manipulation and editing. The course uses the SQLite flavour to give a solid foundation in the principles of relational databases and how to use them.  
    + Query databases  
    + Join tables  
    + Edit tables  
    + Manipulate databases  

# More advanced training  

## Government Analysis Function courses

The Government Analysis Function also offers more advanced courses, for example:  

* [Introduction to Reproducible Analytical Pipelines (RAP)](https://analysisfunction.civilservice.gov.uk/training/introduction-to-reproducible-analytical-pipelines-rap/)  
* [Introduction to sparklyr](https://analysisfunction.civilservice.gov.uk/training/introduction-to-sparklyr/)  
* [Introduction to Pyspark](https://analysisfunction.civilservice.gov.uk/training/introduction-to-pyspark/)  
* [Machine learning in R](https://analysisfunction.civilservice.gov.uk/training/machine-learning-in-r/)  
* [Introduction to machine learning in Python](https://analysisfunction.civilservice.gov.uk/training/introduction-to-machine-learning-in-python/)  

## Geospatial courses

There are lots of resources for undertaking geospatial analysis in Python or R. CDAP has a geospatial cluster which is optimised for running geospatial analysis in Python, therefore making for much faster running of code.  Here are some examples of available courses:

* [University of Helsinki, Automating GIS-processes (Python)](https://autogis-site.readthedocs.io/en/latest/index.html)  
* [University of Liverpool, Geographic Data Science , Dani Arribas-Bel (Python)](https://darribas.org/gds_course/content/home.html)  
* [University of Colorado, EarthLab courses, tutorials and tools, Leah Wasser (Python and R)](https://www.earthdatascience.org/)  
* [University of Chicago, Spatial Data Science tutorials, Luc Anselin (R)](https://spatialanalysis.github.io/tutorials/)  


# Resouces for good practice  

These government resources are relevant for good practice of writing code and undertaking analysis.  

* [Quality Assurance of Code for Analysis and Research](https://best-practice-and-impact.github.io/qa-of-code-guidance/intro.html)  
    + This guide is about quality assurance of code  in government  
    + This includes core programming practices, structuring your project, code documentation, project documentation, version control, configuration, dData management, peer review, and testing code  
* [Reproducible Analytical Pipeline learning materials from the Data Science Campus](https://github.com/datasciencecampus/gov-uk-rap-materials)  
    + These training materials cover Reproducible Analytical Pipelines (RAP)
    + Includes introduction to RAP, using the RMySQL R package, git and git with R presentations and glossaries, tutorial on creating GANTT charts in R, and a template for using RMarkdown to create word documents  
* [Reproducible Analytical Pipeline companion](https://ukgovdatascience.github.io/rap_companion/)  
    + More on Reproducible Analytical Pipelines  
    + Includes chapters on version control, packaging code, unit testing, automated testing, code coverage, dependency and reproducibility, quality assurance of the pipeline, and producing the publication  
* [Spark at the ONS](https://best-practice-and-impact.github.io/ons-spark/intro.html)  
    + For readers familiar with Python or R  
    + If you need to process big data using PySpark in Python or sparklyr in R  
    + Python and R code cells throughout the book to help explain the topics covered 
    
# Table of links
    
| **Task**                                                                             | Training for using RStudio                                  | Training for using Python                                   |
|--------------------------------------------------------------------------------------|-------------------------------------------------------------|-------------------------------------------------------------|
| **Introductory courses**                                                             | [GAF Introduction to R](https://analysisfunction.civilservice.gov.uk/training/introduction-to-r/)                                       | [GAF Introduction to Python](https://analysisfunction.civilservice.gov.uk/training/introduction-to-python/)                                  |
| **Data cleaning and wrangling including merging data and dealing with missing data** | [GAF Data Linkage in R](https://learninghub.ons.gov.uk/enrol/index.php?id=1245)                                       | [GAF Data Linkage in Python](https://learninghub.ons.gov.uk/enrol/index.php?id=1313)                                 |
| ****                                                                                 | [GAF Editing and imputation in R](https://analysisfunction.civilservice.gov.uk/training/editing-and-imputation-in-r/)                             | [GAF Editing and imputation in Python](https://analysisfunction.civilservice.gov.uk/training/editing-and-imputation-in-python/)                        |
| **Data visualisation**                                                               | [GAF Data visualisation in R and Python](https://analysisfunction.civilservice.gov.uk/training/data-visualisation-in-r-and-python/)                      | [GAF Data visualisation in R and Python](https://analysisfunction.civilservice.gov.uk/training/data-visualisation-in-r-and-python/)                      |
| **Creating dashboards**                                                              | [R Shiny dashboards](https://shiny.rstudio.com/tutorial/)                                          |                                                             |
| **Statistical modelling**                                                            | [GAF Statistics in R](https://gss.civilservice.gov.uk/training/statistics-in-r/)                                        |                                                             |
| ****                                                                                 | [Introduction to Bayesian data analysis](https://analysisfunction.civilservice.gov.uk/training/introduction-to-bayesian-data-analysis/)                      | [Introduction to Bayesian data analysis](https://analysisfunction.civilservice.gov.uk/training/introduction-to-bayesian-data-analysis/)                      |
| **Machine learning**                                                                 | [GAF Machine learning in R](https://analysisfunction.civilservice.gov.uk/training/machine-learning-in-r/)                                  | [GAF Machine learning in Python](https://analysisfunction.civilservice.gov.uk/training/introduction-to-machine-learning-in-python/)                             |
| **Spark programming for handling big data**                                          | [GAF Introduction to Sparklyr](https://analysisfunction.civilservice.gov.uk/training/introduction-to-sparklyr/)                                | [GAF Introduction to Pyspark](https://analysisfunction.civilservice.gov.uk/training/introduction-to-pyspark/)                                 |
| **Version control**                                                                  | [GAF command line basics](https://analysisfunction.civilservice.gov.uk/training/command-line-basics/)                                     | [GAF command line basics](https://analysisfunction.civilservice.gov.uk/training/command-line-basics/)                                     |
| ****                                                                                 | [GAF Introduction to git](https://analysisfunction.civilservice.gov.uk/training/introduction-to-git/)                                    | [GAF Introduction to git](https://analysisfunction.civilservice.gov.uk/training/introduction-to-git/)                                     |
| ****                                                                                 | [GitHub skills](https://skills.github.com/)                                               | [GitHub skills](https://skills.github.com/)                                               |
| **Reproducible analytical pipelines (RAP)**                                          | [GAF Introduction to Reproducible Analytical Pipelines (RAP)](https://analysisfunction.civilservice.gov.uk/training/introduction-to-reproducible-analytical-pipelines-rap/) | [GAF Introduction to Reproducible Analytical Pipelines (RAP)](https://analysisfunction.civilservice.gov.uk/training/introduction-to-reproducible-analytical-pipelines-rap/) |
